/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros1.formatting2

import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import ros.Artifact
import ros.CatkinPackage

class Ros1Formatter extends AbstractFormatter2 {

    def dispatch void format(CatkinPackage catkinPackage, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        for (artifact : catkinPackage.artifact) {
            artifact.format
        }
        for (dependency : catkinPackage.dependency) {
            dependency.format
        }
    }

    def dispatch void format(Artifact artifact, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        artifact.node.format
    }

}
