/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros.formatting2

import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import ros.Parameter
import ros.ParameterListType

class BasicsFormatter extends AbstractFormatter2 {

    def dispatch void format(Parameter parameter, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        parameter.type.format
        parameter.namespace.format
    }

    def dispatch void format(ParameterListType parameterListType, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        for (parameterType : parameterListType.sequence) {
            parameterType.format
        }
    }

    // TODO: implement for ParameterStructType, ParameterIntegerType, ParameterStringType, ParameterDoubleType, ParameterDateType, ParameterBooleanType, ParameterBase64Type, ParameterAnyType, ParameterArrayType, ParameterSequence, ParameterStruct, ParameterStructMember, ParameterStructTypeMember, MessagePart
}
