/*
 * generated by Xtext 2.38.0
 */
package de.fraunhofer.ipa.rossystem.scoping;

import de.fraunhofer.ipa.ros.scoping.BasicsScopeProvider;

public abstract class AbstractRosSystemScopeProvider extends BasicsScopeProvider {
}
