/*
 * generated by Xtext 2.38.0
 */
package de.fraunhofer.ipa.ros.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBasicsScopeProvider extends DelegatingScopeProvider {
}
