/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros2.formatting2

import de.fraunhofer.ipa.ros.formatting2.RosFormatter
import org.eclipse.xtext.formatting2.IFormattableDocument
import ros.AmentPackage

class Ros2Formatter extends RosFormatter {

    def dispatch void format(AmentPackage amentPackage, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        for (artifact : amentPackage.artifact) {
            artifact.format
        }
        for (dependency : amentPackage.dependency) {
            dependency.format
        }
    }

}
