/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.rossystem.formatting2

import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import ros.Node
import system.System

class RosSystemFormatter extends AbstractFormatter2 {

    def dispatch void format(System rosSystem, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        for (rosNode : rosSystem.components) {
            rosNode.format
        }
    }

    def dispatch void format(Node node, extension IFormattableDocument document) {
        // TODO: format HiddenRegions around keywords, attributes, cross references, etc.
        for (serviceServer : node.serviceserver) {
            serviceServer.format
        }
        for (publisher : node.publisher) {
            publisher.format
        }
        for (subscriber : node.subscriber) {
            subscriber.format
        }
        for (serviceClient : node.serviceclient) {
            serviceClient.format
        }
        for (actionServer : node.actionserver) {
            actionServer.format
        }
        for (actionClient : node.actionclient) {
            actionClient.format
        }
        for (parameter : node.parameter) {
            parameter.format
        }
    }

    // TODO: implement for ServiceServer, Publisher, Subscriber, ServiceClient, ActionServer, ActionClient, Parameter, ServiceSpec, MessageDefinition, MessagePart, TopicSpec, ActionSpec, ParameterListType, ParameterStructType, ParameterIntegerType, ParameterStringType, ParameterDoubleType, ParameterDateType, ParameterBooleanType, ParameterBase64Type, ParameterAnyType, ParameterArrayType, ParameterSequence, ParameterStructTypeMember, ParameterStruct, ParameterStructMember
}
